name: Run gittuf demo
on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:
jobs:
  run-demo:
    name: Run demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout demo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.13'
      - name: Install gittuf
        uses: gittuf/gittuf-installer@64ada88bdb6d2409e42d9028b29f79bc33695775
        with:
          gittuf-version: 'main'
      - name: Run demo with --no-prompt
        run: |
          python3 run-demo.py --no-prompt
