name: Run gittuf demo
on:
  push:
    branches: ['main']
    paths:
      - 'run-*.py'
      - 'keys/**'
      - '.github/workflows/run-demo.yml'
  pull_request:
    paths:
      - 'run-*.py'
      - 'keys/**'
      - '.github/workflows/run-demo.yml'
  workflow_dispatch:

jobs:
  run-demo:
    name: Run ${{ matrix.demo.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        demo:
          - name: gittuf demo
            script: run-demo.py
          - name: multi-repo demo
            script: run-multi-repo-demo.py
          - name: recovery demo
            script: run-recovery-demo.py
    steps:
      - name: Checkout demo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: '3.13'
      - name: Install gittuf
        uses: gittuf/gittuf-installer@872fe5227186d97f958e6983717942ca0e50384d
        with:
          gittuf-version: 'main'
      - name: Run demo with --no-prompt
        env:
          NO_PROMPT: "1"
        run: |
          python3 ${{ matrix.demo.script }} --no-prompt
