name: Run gittuf demo
on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:
jobs:
  run-demo:
    name: Run demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout demo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          python-version: '3.13'
      - name: Install gittuf
        uses: gittuf/gittuf-installer@a9730b348241599ca1882a8844acb43cd7935bb7
        with:
          gittuf-version: 'main'
      - name: Run demo with --no-prompt
        run: |
          python3 run-demo.py --no-prompt
